#!/usr/bin/env python3

import logging
from TRACK3R import TRACK3RWithClaw

# Change level to logging.INFO to make less chatty
logging.basicConfig(level=logging.DEBUG,
                    format="%(asctime)s %(levelname)5s %(filename)s:%(lineno)5s - %(funcName)25s(): %(message)s")
log = logging.getLogger(__name__)

# Color the errors and warnings in red
logging.addLevelName(logging.ERROR, "\033[91m  %s\033[0m" % logging.getLevelName(logging.ERROR))
logging.addLevelName(logging.WARNING, "\033[91m%s\033[0m" % logging.getLevelName(logging.WARNING))

log.info("Starting TRACK3RWithClaw")
tracker = TRACK3RWithClaw()
tracker.main()
log.info("Exiting TRACK3RWithClaw")
